"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Copy, ExternalLink } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { analyzePublicReport, badgeColor } from "@/lib/public-report";

const riskStyles = {
  Low: "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/40 dark:bg-emerald-500/15 dark:text-emerald-200",
  Medium: "border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-400/40 dark:bg-amber-400/15 dark:text-amber-200",
  High: "border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-400/40 dark:bg-rose-400/15 dark:text-rose-200",
};

const decodeHash = () => {
  if (typeof window === "undefined") return "";
  const match = /^#q=(.+)/.exec(window.location.hash);
  if (!match?.[1]) return "";
  return decodeURIComponent(escape(atob(match[1])));
};

const copyText = async (text: string) => {
  if (navigator.clipboard && window.isSecureContext) {
    await navigator.clipboard.writeText(text);
    return;
  }

  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.body.appendChild(textarea);
  textarea.focus();
  textarea.select();
  document.execCommand("copy");
  document.body.removeChild(textarea);
};

export function PublicReportViewer() {
  const [raw, setRaw] = useState("");
  const [copied, setCopied] = useState<"url" | "badge" | null>(null);

  useEffect(() => {
    queueMicrotask(() => setRaw(decodeHash()));
  }, []);

  const report = useMemo(() => {
    if (!raw) return null;
    try {
      return analyzePublicReport(raw);
    } catch {
      return null;
    }
  }, [raw]);

  if (!report) {
    return (
      <Card className="ai-panel border-border/70 bg-card/90">
        <CardContent className="p-8">
          <Badge className="border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-400/40 dark:bg-amber-400/15 dark:text-amber-200">
            No report data
          </Badge>
          <h1 className="mt-5 text-3xl font-semibold tracking-tight text-foreground">
            Shared report unavailable
          </h1>
          <p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">
            Open the analyzer, run a package.json scan, then use the share report action to generate a public report link.
          </p>
        </CardContent>
      </Card>
    );
  }

  const badgeMarkdown = `[![Package Health](https://img.shields.io/badge/package%20health-${encodeURIComponent(report.healthGrade)}-${badgeColor(report.healthScore)})](${typeof window === "undefined" ? "" : window.location.href})`;

  const handleCopy = async (kind: "url" | "badge") => {
    await copyText(kind === "url" ? window.location.href : badgeMarkdown);
    setCopied(kind);
    setTimeout(() => setCopied(null), 2200);
  };

  return (
    <div className="space-y-6 pb-16">
      <Card className="ai-panel border-border/70 bg-card/90">
        <CardContent className="p-6 sm:p-8">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-start">
            <div>
              <Badge className="border-primary/20 bg-primary/10 text-primary">
                Shared Report
              </Badge>
              <h1 className="mt-5 text-4xl font-semibold tracking-tight text-foreground sm:text-5xl">
                Package Health {report.healthGrade}
              </h1>
              <p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">
                A public dependency snapshot generated by Package Intelligence.
              </p>
            </div>
            <div className="flex flex-wrap gap-2">
              <Button variant="outline" size="sm" onClick={() => void handleCopy("url")}>
                {copied === "url" ? <Check size={14} /> : <Copy size={14} />}
                Copy link
              </Button>
              <Button size="sm" onClick={() => void handleCopy("badge")}>
                {copied === "badge" ? <Check size={14} /> : <ExternalLink size={14} />}
                Copy badge
              </Button>
            </div>
          </div>

          <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {[
              { label: "Health Score", value: `${report.healthScore}/100` },
              { label: "Risk Level", value: report.riskLevel },
              { label: "Expo Compatibility", value: `${report.expoCompatibility}%` },
              { label: "New Architecture", value: `${report.newArchitecture}%` },
            ].map((metric) => (
              <div key={metric.label} className="rounded-3xl border border-border/70 bg-muted/55 px-4 py-4">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
                  {metric.label}
                </p>
                <p className="mt-2 text-2xl font-semibold text-foreground">{metric.value}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-6 lg:grid-cols-[1fr_1fr]">
        <Card className="ai-panel border-border/70 bg-card/90">
          <CardContent className="p-6">
            <div className="flex items-center justify-between gap-3">
              <h2 className="text-xl font-semibold tracking-tight text-foreground">Fix Queue</h2>
              <Badge className={riskStyles[report.riskLevel]}>{report.riskLevel}</Badge>
            </div>
            <div className="mt-5 space-y-3">
              {report.fixQueue.length === 0 ? (
                <p className="text-sm text-muted-foreground">No urgent fixes detected.</p>
              ) : report.fixQueue.map((item) => (
                <div key={`${item.title}-${item.detail}`} className="rounded-2xl border border-border/70 bg-muted/45 px-4 py-3">
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-sm font-semibold text-foreground">{item.title}</p>
                    <Badge className={riskStyles[item.impact]}>{item.impact}</Badge>
                  </div>
                  <p className="mt-2 text-xs leading-5 text-muted-foreground">{item.detail}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="ai-panel border-border/70 bg-card/90">
          <CardContent className="p-6">
            <h2 className="text-xl font-semibold tracking-tight text-foreground">Top Recommendations</h2>
            <div className="mt-5 space-y-3">
              {report.recommendations.length === 0 ? (
                <p className="text-sm text-muted-foreground">No Expo migration recommendations detected.</p>
              ) : report.recommendations.slice(0, 6).map((item) => (
                <div key={`${item.current}-${item.alternative}`} className="rounded-2xl border border-border/70 bg-muted/45 px-4 py-3 text-sm">
                  <span className="font-semibold text-foreground">{item.current}</span>
                  <span className="mx-2 text-muted-foreground">to</span>
                  <span className="font-semibold text-primary">{item.alternative}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
